import type { Contact, DealStatus, DocumentType, Language, Project } from "./types";

export const navItems = [
  "Dashboard",
  "Projects",
  "Investors / Partners",
  "AI Matching",
  "Documents",
  "Deal Pipeline",
  "Settings",
] as const;

export const dealStatuses: DealStatus[] = [
  "Not contacted",
  "Teaser sent",
  "Interested",
  "NDA sent",
  "NDA signed",
  "Data room access granted",
  "Call scheduled",
  "Offer received",
  "Not interested",
  "Closed",
];

export const documentTypes: DocumentType[] = [
  "Executive Summary",
  "Investment Overview",
  "Outreach Email",
];

export const languages: Language[] = ["English", "German"];

export const riskProfiles = [
  "Core",
  "Core-plus",
  "Value-add",
  "Opportunistic",
] as const;

export const emptyProject: Project = {
  name: "",
  location: "",
  city: "",
  country: "Germany",
  assetClass: "Logistics",
  investmentVolume: null,
  purchasePrice: null,
  noi: null,
  rentalIncome: null,
  occupancy: null,
  wault: null,
  capRate: null,
  exitYield: null,
  financingAssumptions: "",
  equityRequirement: null,
  investmentHighlights: "",
  keyRisks: "",
  developmentStatus: "",
  exitStrategy: "",
  googleDriveFolderUrl: "",
  additionalNotes: "",
};

export const emptyContact: Contact = {
  name: "",
  company: "",
  role: "",
  email: "",
  phone: "",
  contactType: "Investor",
  investorProfile: "",
  preferredAssetClasses: ["Logistics"],
  preferredGeographies: ["Germany"],
  ticketSizeMin: null,
  ticketSizeMax: null,
  riskProfile: "Core-plus",
  notes: "",
  relationshipStatus: "New",
};

export const sampleProjects: Project[] = [
  {
    id: 1,
    name: "Riverside Logistics Hub",
    location: "Prime logistics corridor",
    city: "Duesseldorf",
    country: "Germany",
    assetClass: "Logistics",
    investmentVolume: 42500000,
    purchasePrice: 39200000,
    noi: 2450000,
    rentalIncome: 3100000,
    occupancy: 96,
    wault: 6.2,
    capRate: 6.25,
    exitYield: 5.5,
    financingAssumptions:
      "Senior debt at 55 percent LTV with interest-only period under review.",
    equityRequirement: 17800000,
    investmentHighlights:
      "Modern last-mile logistics location\nStrong occupier demand\nReversionary rent potential",
    keyRisks:
      "Lease rollover concentration in year six\nCapex scope requires technical validation",
    developmentStatus: "Standing asset with light value-add plan",
    exitStrategy: "Stabilize rent roll and sell to core buyer after 3 to 5 years",
    googleDriveFolderUrl: "",
    additionalNotes: "Phase 1 sample project for document generation and matching.",
  },
  {
    id: 2,
    name: "Altstadt Mixed-Use Portfolio",
    location: "Central retail and residential blocks",
    city: "Hamburg",
    country: "Germany",
    assetClass: "Mixed-use",
    investmentVolume: 28500000,
    purchasePrice: 27100000,
    noi: 1320000,
    rentalIncome: 1740000,
    occupancy: 91,
    wault: 4.4,
    capRate: 4.87,
    exitYield: 4.35,
    financingAssumptions: "Debt assumptions pending lender feedback.",
    equityRequirement: 12600000,
    investmentHighlights:
      "Central micro-location\nDiversified income base\nResidential rent upside",
    keyRisks: "Retail letting sensitivity\nESG capex still being quantified",
    developmentStatus: "Existing portfolio with active asset management plan",
    exitStrategy: "Refinance or sell individual assets after repositioning",
    googleDriveFolderUrl: "",
    additionalNotes: "Useful for comparing family office fit versus fund fit.",
  },
];

export const sampleContacts: Contact[] = [
  {
    id: 1,
    name: "Anna Weber",
    company: "NordKap Capital",
    role: "Investment Director",
    email: "anna.weber@example.com",
    phone: "+49 30 0000 0000",
    contactType: "Investor",
    investorProfile: "German institutional investor focused on income-producing assets.",
    preferredAssetClasses: ["Logistics", "Office", "Mixed-use"],
    preferredGeographies: ["Germany", "Netherlands", "DACH"],
    ticketSizeMin: 10000000,
    ticketSizeMax: 30000000,
    riskProfile: "Core-plus",
    notes: "Prefers defensible income and clear downside protection.",
    relationshipStatus: "Warm",
  },
  {
    id: 2,
    name: "Markus Stein",
    company: "Stein Family Office",
    role: "Managing Partner",
    email: "markus.stein@example.com",
    phone: "+49 89 0000 0000",
    contactType: "Investor",
    investorProfile: "Family office with selective appetite for German value-add situations.",
    preferredAssetClasses: ["Residential", "Mixed-use", "Hospitality"],
    preferredGeographies: ["Germany", "Austria"],
    ticketSizeMin: 5000000,
    ticketSizeMax: 18000000,
    riskProfile: "Value-add",
    notes: "Needs concise story, local partner credibility, and transparent capex.",
    relationshipStatus: "Active",
  },
  {
    id: 3,
    name: "Sophie Laurent",
    company: "Alpine Debt Partners",
    role: "Capital Partner",
    email: "sophie.laurent@example.com",
    phone: "+41 44 0000 0000",
    contactType: "Partner",
    investorProfile: "Private debt partner for senior and whole-loan structures.",
    preferredAssetClasses: ["Logistics", "Residential", "Office"],
    preferredGeographies: ["DACH", "Germany", "Switzerland"],
    ticketSizeMin: 15000000,
    ticketSizeMax: 60000000,
    riskProfile: "Core",
    notes: "Useful for financing feedback rather than pure equity placement.",
    relationshipStatus: "New",
  },
];
